### ISSUE TITLE
Add license column to Repo

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#10]
remove hardcoded links

https://github.com/wikihouseproject/wikihouse.cc/blob/master/app/models/repo.rb#L25-L31

**Comment by jonleighton** [comment]
We might be able to pull this from the [GitHub license API](https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license)

**Comment by johnrees** [comment]
Yeah, could be perfect if octokit supports the custom Accept header https://developer.github.com/v3/licenses/#markdown-toc

**Comment by jonleighton** [comment]
I've looked into using the GH license API, but it's not ideal:

* It's in beta and the API may change
* It's aimed at software licenses and thus doesn't support creative commons

Therefore, I'll just add license functionality to the CMS.
