### ISSUE TITLE
Have required fields in enquiry forms

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#13]
Related to https://github.com/wikihouseproject/wikihouse.cc/issues/9

What's holding this back is the way the CSS works for the form fields, in that they need to be `<input required...` for the fancy label animations. Fix will likely need to be javascript related.

**Comment by HarryKnight** [comment]
@johnrees this seems to be working now, will close the issue, 'spring cleaning' ;)
