### ISSUE TITLE
Make 'Open Challenges' editable

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#14]
On the bottom left of https://wikihouse.cc/community

Bespoke CMS concern, or should we pull them in from github issues, trello, discourse or another task management system?

Opening the discussion here cc: @jonleighton @HarryKnight @claytonprest @Alastairparvin

**Comment by HarryKnight** [comment]
@johnrees if it's not going to work using projects with some kind of CMS then I think having a viewable Trello board could be the simplest option. It just depends what we want it to do. Each card could include links to Github repo's or issues. Discussion would still happen within Github/wikis. Discourse might be a bit overkill at this stage?

**Comment by jonleighton** [comment]
> Bespoke CMS concern, or should we pull them in from github issues, trello, discourse or another task management system?

I've stuck this in the CMS for now, because it was quick to do. We can of course iterate and pull from elsewhere in the future.
