### ISSUE TITLE
Ability to change current highlighted blog post

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#15]
https://github.com/wikihouseproject/wikihouse.cc/blob/master/app/controllers/static_controller.rb#L21-L28

**Comment by johnrees** [comment]
Might be good to have them as a slider if possible, could share the same Slide 'model' as https://github.com/wikihouseproject/wikihouse.cc/issues/25

**Comment by jonleighton** [comment]
> Might be nice to have the ability to show more than one blog post as a slider if possible, it could share the same Slide 'model' as #25

Agree that this might be nice but in the interest of getting *something* working ASAP, I've not done it for now. I think we should treat it as a future iteration, if it proves desirable.

**Comment by HarryKnight** [comment]
Google Design has a very nice way of laying their stories out. It's a bit more digestible. It would be nice to have the slider but does it break continuity to have one of these kind of 'half page modules' to work as a slider instead of just a block? https://design.google.com/articles/
