### ISSUE TITLE
Ability to manage partner logos and their links

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#17]
![screen shot 2017-02-21 at 10 49 08](https://cloud.githubusercontent.com/assets/601961/23161813/6a5d1d62-f823-11e6-98b3-11ae6648cfd5.png)

**Comment by jonleighton** [comment]
@johnrees I'm working on this as a simple first step. PushType uses [Dragonfly](http://markevans.github.io/dragonfly/) for asset storage, which supports S3 so I think we should go this route. Does WikiHouse already have an AWS account? Should I create one? (BTW I like using https://www.terraform.io/ for configuring cloud resources, so happy to set that up if you agree.)

**Comment by johnrees** [comment]
I don't think WH has an AWS account, but I'll do some digging tonight be sure. Could you use a personal one just for testing over the next 24hrs?

Yep Dragonfly's fine. The only issue I have with it and carrierwave/paperclip, if I'm not mistaken, is that the the app server then acts as a proxy between you sending the file and S3 receiving it, rather than sending the file directly to S3 from your browser.

For our needs that'll be a non-issue, but it becomes one when you start uploading big files i.e. requests longer than 30s will timeout on heroku https://devcenter.heroku.com/articles/request-timeout#uploading-large-files

Been meaning to try Terraform for a while, yes go for it! As a sidenote, this looks pretty nice https://github.com/wallix/awless
