### ISSUE TITLE
Editable FAQ section

### ISSUE THREAD

**Issue by johnrees** [wikihouseproject/wikihouse.cc#19]
tab on https://wikihouse.cc/about

![screen shot 2017-02-21 at 10 51 54](https://cloud.githubusercontent.com/assets/601961/23161888/c94c8ae2-f823-11e6-96a9-8adf2a10bd5c.png)

**Comment by johnrees** [comment]
"potentially looking at developing a knowledge base on [Gitbooks](https://www.gitbook.com/)" - @HarryKnight

**Comment by jonleighton** [comment]
@Alastairparvin @HarryKnight Could you clarify whether I should implement this? (FWIW, it'll be pretty quick and easy to do)

**Comment by HarryKnight** [comment]
@jonleighton yip but let's have a catch up before hand over hangouts.
