### ISSUE TITLE
Use code climate

### ISSUE THREAD

**Issue by jonleighton** [wikihouseproject/wikihouse.cc#26]

**Comment by johnrees** [comment]
Added the repo to codeclimate

Code quality badges in readme https://github.com/wikihouseproject/wikihouse.cc/commit/fd8e2f11c140a7bc05a1f14355940c9ce016bbfe

Test coverage could be added if you think it's beneficial, not sure how pertinent it'd be to this project though

**Comment by jonleighton** [comment]
I think we should add tests as we go along, when we touch the more complex bits of code
