### ISSUE TITLE
Fix brakeman warning

### ISSUE THREAD

**Issue by jonleighton** [wikihouseproject/wikihouse.cc#37]
https://codeclimate.com/github/wikihouseproject/wikihouse.cc/app/views/things/show.html.erb

**Comment by johnrees** [comment]
related https://github.com/wikihouseproject/wikihouse.cc/issues/10

**Comment by jonleighton** [comment]
Ok, on closer inspection this is clearly a false positive which will go away when #10 is done, so let's not worry for now
